http:
  middlewares:
    crowdsec-traefik:
      plugin:
        crowdsec-bouncer:
          enabled: "true"
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiKey: {{ env "CROWDSEC_LAPI_KEY" }}
          crowdsecMode: "stream"
          updateIntervalSeconds: "10"
