tls:
  certificates:
    - certFile: {{ env "PUBLIC_CERT_FILE" }}
      keyFile: {{ env "PUBLIC_CERT_KEY" }}
    - certFile: {{ env "PRIVATE_CERT_FILE" }}
      keyFile: {{ env "PRIVATE_CERT_KEY" }}
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384
