name: "Stalwart_email"

services:
  stalwart-email:
    container_name: "stalwart-email"
    hostname: "stalwart-email"
    image: "stalwartlabs/mail-server:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.stalwart.entrypoints: "websecure"
      traefik.http.routers.stalwart.rule: "Host(`autodiscover.repinger.com`)\
                                          || Host(`autoconfig.repinger.com`) || Host(`mta-sts.repinger.com`)\
                                          || Host(`${STALWART_DOMAIN}`)"
      traefik.http.routers.stalwart.service: "stalwart"
      traefik.http.routers.stalwart.tls: "true"
      traefik.http.routers.stalwart.tls.options: "private@file"
      traefik.http.services.stalwart.loadbalancer.server.port: "8080"
    networks:
      - "infra-1"
    ports:
      - "${PUBLIC_IP_IPV4}:25:25"
      - "${PUBLIC_IP_IPV4}:465:465"
      - "${PUBLIC_IP_IPV4}:993:993"
      - "${PUBLIC_IP_IPV4}:995:995"
      - "${PUBLIC_IP_IPV6}:25:25"
      - "${PUBLIC_IP_IPV6}:465:465"
      - "${PUBLIC_IP_IPV6}:993:993"
      - "${PUBLIC_IP_IPV6}:995:995"
    restart: "always"
    volumes:
      - "./stalwart:/opt/stalwart-mail"
      - "/etc/localtime:/etc/localtime:ro"
      - "../acme.sh/certs:/certs:ro"

  snappymail:
    container_name: "snappymail"
    depends_on:
        - "stalwart-email"
        - "traefik"
    hostname: "snappymail"
    image: "djmaze/snappymail:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.wg-local-accesslist.ipallowlist.sourcerange: "${PRIVATE_IPV4_SUBNET}, ${PRIVATE_IPV6_SUBNET}"
      traefik.http.routers.snappymail.entrypoints: "websecure"
      traefik.http.routers.snappymail.middlewares: "wg-local-accesslist"
      traefik.http.routers.snappymail.rule: "Host(`${SNAPPYMAIL_DOMAIN}`)"
      traefik.http.routers.snappymail.service: "snappymail"
      traefik.http.routers.snappymail.tls: "true"
      traefik.http.routers.snappymail.tls.options: "private@file"
      traefik.http.services.snappymail.loadbalancer.server.port: "8888"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "./snappymail:/var/lib/snappymail"
