name: "Stalwart_email"

services:
  stalwart-email:
    container_name: "stalwart-email"
    hostname: "stalwart-email"
    image: "stalwartlabs/mail-server:latest"
    environment:
      TZ: "${TZ:-UTC}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.stalwart.entrypoints: "websecure"
      traefik.http.routers.stalwart.rule: "(
        Host(`autodiscover.repinger.com`) || 
        Host(`autoconfig.repinger.com`) || 
        Host(`mta-sts.repinger.com`) || 
        Host(`${STALWART_DOMAIN}`) || 
        Host(`mail.repinger.com`)
      )"
      traefik.http.routers.stalwart.service: "stalwart"
      traefik.http.routers.stalwart.tls: "true"
      traefik.http.services.stalwart.loadbalancer.server.port: "8080"
    networks:
      - "infra-1"
    ports:
      - "${PUBLIC_IP_IPV4}:25:25/tcp"
      - "${PUBLIC_IP_IPV4}:465:465/tcp"
      - "${PUBLIC_IP_IPV4}:993:993/tcp"
      - "${PUBLIC_IP_IPV6}:25:25/tcp"
      - "${PUBLIC_IP_IPV6}:465:465/tcp"
      - "${PUBLIC_IP_IPV6}:993:993/tcp"
    restart: "always"
    volumes:
      - "./stalwart:/opt/stalwart-mail"
      - "../acme.sh/certs:/certs:ro"
