name: "dns"

services:
  adguardhome:
    container_name: "adguardhome"
    depends_on:
      - "bind9"
    environment:
      TZ: "${TZ:-UTC}"
    healthcheck:
      test: ["CMD", "nslookup", "${ADGUARDHOME_DOMAIN}", "::1"]
      interval: 10s
      timeout: 4s
      retries: 3
      start_period: 7s
    hostname: "adguardhome"
    image: "adguard/adguardhome:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguardhome.entrypoints: "websecure"
      traefik.http.routers.adguardhome.middlewares: "wg-local-accesslist@file,pocketid-oidc-auth@file"
      traefik.http.routers.adguardhome.rule: "Host(`${ADGUARDHOME_DOMAIN}`)"
      traefik.http.routers.adguardhome.service: "adguardhome"
      traefik.http.routers.adguardhome.tls: "true"
      traefik.http.services.adguardhome.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    ports:
      - "${PRIVATE_IPV4}:53:53/tcp"
      - "${PRIVATE_IPV4}:53:53/udp"
      - "${PUBLIC_IP_IPV4}:853:853/tcp"
      - "${PUBLIC_IP_IPV4}:853:853/udp"
      - "${PRIVATE_IPV6}:53:53/tcp"
      - "${PRIVATE_IPV6}:53:53/udp"
      - "${PUBLIC_IP_IPV6}:853:853/tcp"
      - "${PUBLIC_IP_IPV6}:853:853/udp"
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "[::1]:53:53/tcp"
      - "[::1]:53:53/udp"
    restart: "always"
    volumes:
      - "./adguardhome/conf:/opt/adguardhome/conf"
      - "./adguardhome/work:/opt/adguardhome/work"
      - "../acme.sh/certs:/certs:ro"

  bind9:
    container_name: "bind9"
    hostname: "bind9"
    image: "ubuntu/bind9:latest"
    environment:
      BIND9_USER: "root"
      TZ: "${TZ:-UTC}"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "./bind9/config:/etc/bind:ro"
      - "./bind9/cache:/var/cache/bind"

  doh-server:
    container_name: "doh-server"
    hostname: "doh-server"
    depends_on:
      adguardhome:
        condition: service_healthy
    image: "repinger/doh-server:latest"
    environment:
      TZ: "${TZ:-UTC}"
    labels:
      traefik.enable: "true"

      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.Cache-Control: "public, max-age=240"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.Content-Security-Policy: "default-src 'none'"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), unload=(), window-placement=(), vertical-scroll=()"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.Server: ""
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.X-Content-Type-Options: "nosniff"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.X-Frame-Options: "DENY"
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.X-Powered-By: ""
      traefik.http.middlewares.doh-server-header.headers.customresponseheaders.X-Xss-Protection: "0"

      traefik.http.routers.doh-server.entrypoints: "websecure"
      traefik.http.routers.doh-server.middlewares: "crowdsec-traefik@file,doh-server-header"
      traefik.http.routers.doh-server.rule: "(
        Host(`doh.repinger.my.id`) || 
        Host(`dns.repinger.my.id`) || 
        Host(`dot.repinger.my.id`) || 
        Host(`doh.repinger.com`) || 
        Host(`dns.repinger.com`) || 
        Host(`dot.repinger.com`)
      ) && PathPrefix(`/dns-query`)"
      traefik.http.routers.doh-server.service: "doh-server"
      traefik.http.routers.doh-server.tls: "true"
      traefik.http.services.doh-server.loadbalancer.server.port: "3000"
    networks:
      - "infra-1"
    restart: "always"
