name: "monitoring"

services:
  grafana:
    container_name: "grafana"
    depends_on:
      endlessh:
        condition: service_started
      prometheus:
        condition: service_healthy
    environment:
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://${POCKET_ID_DOMAIN}/api/oidc/userinfo"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://${POCKET_ID_DOMAIN}/authorize"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${GRAFANA_OAUTH_CLIENT_ID}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GRAFANA_OAUTH_CLIENT_SECRET}"
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME: "email:primary"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Pocket ID"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
      GF_AUTH_GENERIC_OAUTH_SKIP_ORG_AUTH_SYNC: "true"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://${POCKET_ID_DOMAIN}/api/oidc/token"
      GF_SERVER_ROOT_URL: "https://${GRAFANA_DOMAIN}"

      TZ: "${TZ:-UTC}"
    healthcheck:
      test: ["CMD", "curl", '-s', '-H', 'application/json', 'http://grafana:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    hostname: "grafana"
    image: "grafana/grafana-oss:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.middlewares: "wg-local-accesslist@file"
      traefik.http.routers.grafana.rule: "Host(`${GRAFANA_DOMAIN}`)"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
    networks:
      - "infra-1"
    restart: "always"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - "./grafana:/var/lib/grafana"

  prometheus:
    container_name: "prometheus"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://prometheus:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    hostname: "prometheus"
    image: "prom/prometheus:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.middlewares: "wg-local-accesslist@file,pocketid-oidc-auth@file"
      traefik.http.routers.prometheus.rule: "Host(`${PROMETHEUS_DOMAIN}`)"
      traefik.http.routers.prometheus.service: "prometheus"
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
    networks:
      - "infra-1"
    restart: "always"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - "./prometheus/config:/etc/prometheus"
      - "./prometheus/data:/prometheus"
      - "/etc/localtime:/etc/localtime:ro"
