name: "monitoring"

services:
  grafana:
    container_name: "grafana"
    depends_on:
      - "endlessh"
    environment:
      TZ: "${TZ:-UTC}"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_SERVER_ROOT_URL: "https://${GRAFANA_DOMAIN}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${GRAFANA_OAUTH_CLIENT_ID}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GRAFANA_OAUTH_CLIENT_SECRET}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://${AUTHENTIK_DOMAIN}/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://${AUTHENTIK_DOMAIN}/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://${AUTHENTIK_DOMAIN}/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://${AUTHENTIK_DOMAIN}/application/o/grafana/end-session/"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
    hostname: "grafana"
    image: "grafana/grafana-oss:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.wg-local-accesslist.ipallowlist.sourcerange: "${PRIVATE_IPV4_SUBNET}, ${PRIVATE_IPV6_SUBNET}"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.middlewares: "wg-local-accesslist"
      traefik.http.routers.grafana.rule: "Host(`${GRAFANA_DOMAIN}`)"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
    networks:
      - "infra-1"
    restart: "always"
    user: ${GRAFANA_USER_ID}
    volumes:
      - "./grafana:/var/lib/grafana"

  prometheus:
    container_name: "prometheus"
    hostname: "prometheus"
    image: "prom/prometheus:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.wg-local-accesslist.ipallowlist.sourcerange: "${PRIVATE_IPV4_SUBNET}, ${PRIVATE_IPV6_SUBNET}"
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.middlewares: "wg-local-accesslist,authentik-middleware@file"
      traefik.http.routers.prometheus.rule: "Host(`${PROMETHEUS_DOMAIN}`)"
      traefik.http.routers.prometheus.service: "prometheus"
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
    networks:
      - "infra-1"
    restart: "always"
    user: ${PROMETHEUS_USER_ID}
    volumes:
      - "./prometheus/config:/etc/prometheus"
      - "./prometheus/data:/prometheus"
      - "/etc/localtime:/etc/localtime:ro"
