name: "traefik"

services:
  traefik:
    container_name: "traefik"
    depends_on:
      adguardhome:
        condition: service_healthy
      anubis:
        condition: service_healthy
      crowdsec:
        condition: service_started
      doh-server:
        condition: service_healthy
      grafana:
        condition: service_started
      web-blackhole:
        condition: service_started
      web-dns:
        condition: service_started
      web-files:
        condition: service_started
      web-main:
        condition: service_started
      web-storage:
        condition: service_started
      pocket-id:
        condition: service_healthy
      prometheus:
        condition: service_started
      stalwart-email:
        condition: service_started
    environment:
      CROWDSEC_LAPI_KEY: "${TRAEFIK_CROWDSEC_LAPI_KEY}"

      OIDC_SECRET: "${TRAEFIK_OIDC_SECRET}"

      PRIVATE_CERT_FILE: "${TRAEFIK_PRIVATE_CERT_FILE}"
      PRIVATE_CERT_KEY: "${TRAEFIK_PRIVATE_CERT_KEY}"

      PRIVATE_IPV4_RANGE: "${PRIVATE_IPV4_SUBNET}"
      PRIVATE_IPV6_RANGE: ${PRIVATE_IPV6_SUBNET}

      POCKETID_OIDC_AUTH_URL: "${POCKET_ID_DOMAIN}"
      POCKETID_OIDC_AUTH_CLIENT_ID: "${TRAEFIK_POCKET_ID_CID}"
      POCKETID_OIDC_AUTH_CLIENT_SECRET: "${TRAEFIK_POCKET_ID_SECRET}"

      PUBLIC_CERT_FILE: "${TRAEFIK_PUBLIC_CERT_FILE}"
      PUBLIC_CERT_KEY: "${TRAEFIK_PUBLIC_CERT_KEY}"

      TZ: "${TZ:-UTC}"
    hostname: "traefik"
    image: "traefik:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboard.entrypoints: "websecure"
      traefik.http.routers.traefik-dashboard.middlewares: "wg-local-accesslist@file,pocketid-oidc-auth@file"
      traefik.http.routers.traefik-dashboard.rule: "Host(`${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.traefik-dashboard.service: "traefik-dashboard"
      traefik.http.routers.traefik-dashboard.tls: "true"
      traefik.http.services.traefik-dashboard.loadbalancer.server.port: "8080"
    networks:
      - "infra-1"
    ports:
      - "${PRIVATE_IPV4}:80:80/tcp"
      - "${PRIVATE_IPV4}:443:443/tcp"
      - "${PRIVATE_IPV4}:443:443/udp"
      - "${PUBLIC_IP_IPV4}:80:80/tcp"
      - "${PUBLIC_IP_IPV4}:443:443/tcp"
      - "${PUBLIC_IP_IPV4}:443:443/udp"
      - "${PRIVATE_IPV6}:80:80/tcp"
      - "${PRIVATE_IPV6}:443:443/tcp"
      - "${PRIVATE_IPV6}:443:443/udp"
      - "${PUBLIC_IP_IPV6}:80:80/tcp"
      - "${PUBLIC_IP_IPV6}:443:443/tcp"
      - "${PUBLIC_IP_IPV6}:443:443/udp"
    restart: "always"
    volumes:
      - "../acme.sh/certs:/certs:ro"
      - "./config:/etc/traefik:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/var/log/traefik"

  anubis:
    container_name: "anubis"
    environment:
      BIND: ":8080"
      COOKIE_EXPIRATION_TIME: "8h"
      ED25519_PRIVATE_KEY_HEX: "${ANUBIS_PRIVATE_KEY}"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://traefik:3923"
      TZ: "${TZ:-UTC}"
      WEBMASTER_EMAIL: ${ANUBIS_WEBMASTER_EMAIL}
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    hostname: "anubis"
    image: "ghcr.io/techarohq/anubis:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.anubis.entrypoints: "websecure"
      traefik.http.routers.anubis.rule: "PathRegexp(`.*`)"
      traefik.http.routers.anubis.service: "anubis"
      traefik.http.routers.anubis.tls: "true"
      traefik.http.services.anubis.loadbalancer.server.port: "8080"
      traefik.http.routers.anubis.priority: "1"
    networks:
      - "infra-1"
