name: "traefik"

services:
  traefik:
    container_name: "traefik"
    depends_on:
      - "adguardhome"
      - "authentik-server"
      - "authentik-worker"
      - "crowdsec"
      - "doh-server"
      - "grafana"
      - "web-blackhole"
      - "web-dns"
      - "web-files"
      - "web-main"
      - "web-storage"
      - "prometheus"
      - "snappymail"
      - "stalwart-email"
    environment:
      CROWDSEC_LAPI_KEY: "${TRAEFIK_CROWDSEC_LAPI_KEY}"

      PRIVATE_CERT_FILE: "${TRAEFIK_PRIVATE_CERT_FILE}"
      PRIVATE_CERT_KEY: "${TRAEFIK_PRIVATE_CERT_KEY}"

      PRIVATE_IPV4_RANGE: "${PRIVATE_IPV4_SUBNET}"
      PRIVATE_IPV6_RANGE: ${PRIVATE_IPV6_SUBNET}

      PUBLIC_CERT_FILE: "${TRAEFIK_PUBLIC_CERT_FILE}"
      PUBLIC_CERT_KEY: "${TRAEFIK_PUBLIC_CERT_KEY}"

      TZ: "${TZ:-UTC}"
    hostname: "traefik"
    image: "traefik:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboard.entrypoints: "websecure"
      traefik.http.routers.traefik-dashboard.middlewares: "wg-local-accesslist@file,authentik@file"
      traefik.http.routers.traefik-dashboard.rule: "Host(`${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.traefik-dashboard.service: "traefik-dashboard"
      traefik.http.routers.traefik-dashboard.tls: "true"
      traefik.http.services.traefik-dashboard.loadbalancer.server.port: "8080"
    networks:
      - "infra-1"
    ports:
      - "${PRIVATE_IPV4}:80:80/tcp"
      - "${PRIVATE_IPV4}:443:443/tcp"
      - "${PRIVATE_IPV4}:443:443/udp"
      - "${PUBLIC_IP_IPV4}:80:80/tcp"
      - "${PUBLIC_IP_IPV4}:443:443/tcp"
      - "${PUBLIC_IP_IPV4}:443:443/udp"
      - "${PRIVATE_IPV6}:80:80/tcp"
      - "${PRIVATE_IPV6}:443:443/tcp"
      - "${PRIVATE_IPV6}:443:443/udp"
      - "${PUBLIC_IP_IPV6}:80:80/tcp"
      - "${PUBLIC_IP_IPV6}:443:443/tcp"
      - "${PUBLIC_IP_IPV6}:443:443/udp"
    restart: "always"
    volumes:
      - "../acme.sh/certs:/certs:ro"
      - "./config:/etc/traefik:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/var/log/traefik"
