name: "rclone"

services:
  rclone:
    cap_add:
      - SYS_ADMIN
    command:
      - "mount"
      - "${RSYNC_BUCKET_NAME}:"
      - "${RSYNC_MOUNT_DIR}"
      - "--allow-non-empty"
    container_name: "rclone"
    devices:
      - "/dev/fuse"
    environment:
      PHP_TZ: "${TZ:-UTC}"
      TZ: "${TZ:-UTC}"
    hostname: "rclone"
    image: "rclone/rclone:latest"
    networks:
      - "infra-1"
    restart: "always"
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - "/etc/group:/etc/group:ro"
      - "/etc/passwd:/etc/passwd:ro"
      - "${RSYNC_MOUNT_HOST_DIR}${RSYNC_MOUNT_DIR}:${RSYNC_MOUNT_DIR}:shared"  # Cloudflare R2 mount
      - "./config:/config/rclone"
