name: "web"

services:
  nginx-blackhole:
    container_name: "nginx-blackhole"
    hostname: "nginx-blackhole"
    depends_on:
      - "traefik"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.web-comp.compress: "true"
      traefik.http.middlewares.web-comp.compress.defaultEncoding: "br"
      traefik.http.routers.nginx-blackhole.entrypoints: "websecure"
      traefik.http.routers.nginx-blackhole.middlewares: "web-comp"
      traefik.http.routers.nginx-blackhole.rule: "Host(`mail.repinger.com`) && Path(`/`)\
                                                  || Host(`evan.repinger.com`)\
                                                  || Host(`autodiscover.repinger.com`) && Path(`/`)\
                                                  || Host(`autoconfig.repinger.com`) && Path(`/`)\
                                                  || Host(`mta-sts.repinger.com`) && Path(`/`)"
      traefik.http.routers.nginx-blackhole.service: "nginx-blackhole"
      traefik.http.routers.nginx-blackhole.tls: "true"
      traefik.http.routers.nginx-blackhole.tls.options: "public@file"
      traefik.http.services.nginx-blackhole.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_WEB_DIR}:/var/www"

  nginx-dns:
    container_name: "nginx-dns"
    hostname: "nginx-dns"
    depends_on:
      - "doh-server"
      - "traefik"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.web-comp.compress: "true"
      traefik.http.middlewares.web-comp.compress.defaultEncoding: "br"
      traefik.http.middlewares.crowdsec-traefik.plugin.crowdsec-bouncer.crowdseclapihost: "crowdsec:8080"
      traefik.http.middlewares.crowdsec-traefik.plugin.crowdsec-bouncer.crowdseclapikey: "${CROWDSEC_LAPI_KEY}"
      traefik.http.middlewares.crowdsec-traefik.plugin.crowdsec-bouncer.crowdsecmode: "stream"
      traefik.http.middlewares.crowdsec-traefik.plugin.crowdsec-bouncer.enabled: "true"
      traefik.http.routers.nginx-dns.entrypoints: "websecure"
      traefik.http.routers.nginx-dns.middlewares: "crowdsec-traefik,web-comp"
      traefik.http.routers.nginx-dns.rule: "Host(`doh.repinger.my.id`) || Host(`dns.repinger.my.id`) || Host(`dot.repinger.my.id`)\
                                            || Host(`doh.repinger.com`) || Host(`dns.repinger.com`) || Host(`dot.repinger.com`)"
      traefik.http.routers.nginx-dns.service: "nginx-dns"
      traefik.http.routers.nginx-dns.tls: "true"
      traefik.http.routers.nginx-dns.tls.options: "public@file"
      traefik.http.services.nginx-dns.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_WEB_DIR}:/var/www"

  nginx-files:
    container_name: "nginx-files"
    hostname: "nginx-files"
    image: "macbre/nginx-http3:latest"
    depends_on:
      - "php-fpm"
      - "traefik"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.cf-ips-accesslist.ipallowlist.sourcerange: "173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18, 108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17, 162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22, 2400:cb00::/32, 2606:4700::/32, 2803:f800::/32, 2405:b500::/32, 2405:8100::/32, 2a06:98c0::/29, 2c0f:f248::/32"
      traefik.http.middlewares.web-comp.compress: "true"
      traefik.http.middlewares.web-comp.compress.defaultEncoding: "br"
      traefik.http.routers.nginx-files.entrypoints: "websecure"
      traefik.http.routers.nginx-files.middlewares: "web-comp,cf-ips-accesslist"
      traefik.http.routers.nginx-files.rule: "Host(`files.repinger.my.id`) || Host(`files.repinger.com`)\
                                              || Host(`file.repinger.my.id`) || Host(`file.repinger.com`)"
      traefik.http.routers.nginx-files.service: "nginx-files"
      traefik.http.routers.nginx-files.tls: "true"
      traefik.http.routers.nginx-files.tls.options: "public@file"
      traefik.http.services.nginx-files.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_WEB_DIR}:/var/www"

  nginx-storage:
    container_name: "nginx-storage"
    depends_on:
      - "traefik"
    hostname: "nginx-storage"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.cf-ips-accesslist.ipallowlist.sourcerange: "173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18, 108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17, 162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22, 2400:cb00::/32, 2606:4700::/32, 2803:f800::/32, 2405:b500::/32, 2405:8100::/32, 2a06:98c0::/29, 2c0f:f248::/32"
      traefik.http.middlewares.web-comp.compress: "true"
      traefik.http.middlewares.web-comp.compress.defaultEncoding: "br"
      traefik.http.routers.nginx-storage.entrypoints: "websecure"
      traefik.http.routers.nginx-storage.middlewares: "cf-ips-accesslist"
      traefik.http.routers.nginx-storage.rule: "Host(`storage.repinger.com`) || Host(`dump.repinger.com`)"
      traefik.http.routers.nginx-storage.service: "nginx-storage"
      traefik.http.routers.nginx-storage.tls: "true"
      traefik.http.routers.nginx-storage.tls.options: "public@file"
      traefik.http.services.nginx-storage.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_WEB_DIR}:/var/www"

  nginx-web:
    container_name: "nginx-web"
    depends_on:
      - "traefik"
    hostname: "nginx-web"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.cf-ips-accesslist.ipallowlist.sourcerange: "173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18, 108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17, 162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22, 2400:cb00::/32, 2606:4700::/32, 2803:f800::/32, 2405:b500::/32, 2405:8100::/32, 2a06:98c0::/29, 2c0f:f248::/32"
      traefik.http.middlewares.web-comp.compress: "true"
      traefik.http.middlewares.web-comp.compress.defaultEncoding: "br"
      traefik.http.routers.nginx-web.entrypoints: "websecure"
      traefik.http.routers.nginx-web.middlewares: "web-comp,cf-ips-accesslist"
      traefik.http.routers.nginx-web.rule: "Host(`repinger.my.id`) || Host(`www.repinger.my.id`)\
                                            || Host(`repinger.com`) || Host(`www.repinger.com`)"
      traefik.http.routers.nginx-web.service: "nginx-web"
      traefik.http.routers.nginx-web.tls: "true"
      traefik.http.routers.nginx-web.tls.options: "public@file"
      traefik.http.services.nginx-web.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_WEB_DIR}:/var/www"

  php-fpm:
    container_name: "php-fpm"
    hostname: "php-fpm"
    image: "php:8.1-fpm-alpine"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${NGINX_WEB_DIR}:/var/www"
