name: "web"

services:
  web-blackhole:
    container_name: "web-blackhole"
    environment:
      TZ: "${TZ:-UTC}"
    hostname: "web-blackhole"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.web-blackhole.entrypoints: "websecure"
      traefik.http.routers.web-blackhole.middlewares: "web-comp@file"
      traefik.http.routers.web-blackhole.rule: "(
        Host(`mail.repinger.com`) && (Path(`/`) || Path(`/login`)) ||
        Host(`autodiscover.repinger.com`) && (Path(`/`) || Path(`/login`)) ||
        Host(`autoconfig.repinger.com`) && (Path(`/`) || Path(`/login`)) ||
        Host(`mta-sts.repinger.com`) && (Path(`/`) || Path(`/login`)) ||
        Host(`evan.repinger.com`) ||
        Host(`file.repinger.com`) ||
        Host(`file.repinger.my.id`) ||
        Host(`files.repinger.my.id`) ||
        Host(`repinger.my.id`) ||
        Host(`www.repinger.my.id`) ||
        Host(`www.repinger.com`) ||
        Host(`dns.repinger.my.id`) && !Path(`/dns-query`) ||
        Host(`doh.repinger.my.id`) && !Path(`/dns-query`) ||
        Host(`dot.repinger.my.id`) && !Path(`/dns-query`) ||
        Host(`doh.repinger.com`) && !Path(`/dns-query`) ||
        Host(`dot.repinger.com`) && !Path(`/dns-query`))"
      traefik.http.routers.web-blackhole.service: "web-blackhole"
      traefik.http.routers.web-blackhole.tls: "true"
      traefik.http.services.web-blackhole.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "./config/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "${WEB_DIR}:/var/www"

  web-dns:
    container_name: "web-dns"
    environment:
      TZ: "${TZ:-UTC}"
    hostname: "web-dns"
    image: "repinger/dns-webpage:latest"
    labels:
      traefik.enable: "true"

      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Cache-Control: "public, no-cache"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Content-Security-Policy: "default-src 'none'; style-src 'self'; img-src 'self'"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Server: ""
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.X-Content-Type-Options: "nosniff"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Referrer-Policy: "no-referrer"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Cross-Origin-Opener-Policy: "same-origin"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Cross-Origin-Embedder-Policy: "require-corp"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.Origin-Agent-Cluster: "?1"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.X-Frame-Options: "DENY"
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.X-Powered-By: ""
      traefik.http.middlewares.dns-webpage-header.headers.customresponseheaders.X-Xss-Protection: "0"

      traefik.http.routers.web-dns.entrypoints: "websecure"
      traefik.http.routers.web-dns.middlewares: "crowdsec-traefik@file,web-comp@file,dns-webpage-header"
      traefik.http.routers.web-dns.rule: "Host(`dns.repinger.com`)"
      traefik.http.routers.web-dns.service: "web-dns"
      traefik.http.routers.web-dns.tls: "true"
      traefik.http.services.web-dns.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"

  web-files:
    container_name: "web-files"
    environment:
      TZ: "${TZ:-UTC}"
    hostname: "web-files"
    image: "caddy:alpine"
    labels:
      traefik.enable: "true"
      traefik.http.routers.web-files.entrypoints: "websecure"
      traefik.http.routers.web-files.middlewares: "web-comp@file,cf-ips-accesslist@file,web-files-headers"
      traefik.http.routers.web-files.rule: "Host(`files.repinger.com`)"
      traefik.http.routers.web-files.service: "web-files"
      traefik.http.routers.web-files.tls: "true"
      traefik.http.services.web-files.loadbalancer.server.port: "80"

      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(self), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.X-Content-Type-Options: "nosniff"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Referrer-Policy: "no-referrer"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Cross-Origin-Opener-Policy: "same-origin"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Cross-Origin-Embedder-Policy: "require-corp"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.Origin-Agent-Cluster: "?1"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.X-Frame-Options: "DENY"
      traefik.http.middlewares.web-files-headers.headers.customresponseheaders.X-Xss-Protection: "0"
    networks:
      - "infra-1"
    restart: "always"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - "./config/caddy:/etc/caddy:ro"
      - "${WEB_DIR}:/var/www"

  web-storage:
    container_name: "web-storage"
    environment:
      TZ: "${TZ:-UTC}"
    hostname: "web-storage"
    image: "macbre/nginx-http3:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.web-storage.entrypoints: "websecure"
      traefik.http.routers.web-storage.middlewares: "web-comp@file,cf-ips-accesslist@file"
      traefik.http.routers.web-storage.rule: "Host(`storage.repinger.com`) || Host(`dump.repinger.com`)"
      traefik.http.routers.web-storage.service: "web-storage"
      traefik.http.routers.web-storage.tls: "true"
      traefik.http.services.web-storage.loadbalancer.server.port: "80"
    networks:
      - "infra-1"
    restart: "always"
    volumes:
      - "./config/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "${WEB_DIR}:/var/www"

  web-main:
    container_name: "web-main"
    environment:
      TZ: "${TZ:-UTC}"
    hostname: "web-main"
    image: "repinger/main-webpage:latest"
    labels:
      traefik.enable: "true"

      traefik.http.routers.web-main.entrypoints: "websecure"
      traefik.http.routers.web-main.middlewares: "web-comp@file,main-webpage-header,cf-ips-accesslist@file"
      traefik.http.routers.web-main.rule: "Host(`repinger.com`)"
      traefik.http.routers.web-main.service: "web-main"
      traefik.http.routers.web-main.tls: "true"
      traefik.http.services.web-main.loadbalancer.server.port: "80"

      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Cache-Control: "public, no-cache"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Content-Security-Policy: "default-src 'none'; style-src 'self'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self'"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(self), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Server: ""
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.X-Content-Type-Options: "nosniff"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Referrer-Policy: "no-referrer"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Cross-Origin-Opener-Policy: "same-origin"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Cross-Origin-Embedder-Policy: "require-corp"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.Origin-Agent-Cluster: "?1"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.X-Frame-Options: "DENY"
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.X-Powered-By: ""
      traefik.http.middlewares.main-webpage-header.headers.customresponseheaders.X-Xss-Protection: "0"
    networks:
      - "infra-1"
    restart: "always"
